import { useState } from 'react';

const areaCodes: Record<string, { city: string; state: string; tz: string }> = {
  '201': { city: 'Jersey City', state: 'NJ', tz: 'Eastern' }, '202': { city: 'Washington', state: 'DC', tz: 'Eastern' },
  '203': { city: 'Bridgeport', state: 'CT', tz: 'Eastern' }, '205': { city: 'Birmingham', state: 'AL', tz: 'Central' },
  '206': { city: 'Seattle', state: 'WA', tz: 'Pacific' }, '207': { city: 'Portland', state: 'ME', tz: 'Eastern' },
  '208': { city: 'Boise', state: 'ID', tz: 'Mountain' }, '209': { city: 'Stockton', state: 'CA', tz: 'Pacific' },
  '210': { city: 'San Antonio', state: 'TX', tz: 'Central' }, '212': { city: 'New York', state: 'NY', tz: 'Eastern' },
  '213': { city: 'Los Angeles', state: 'CA', tz: 'Pacific' }, '214': { city: 'Dallas', state: 'TX', tz: 'Central' },
  '215': { city: 'Philadelphia', state: 'PA', tz: 'Eastern' }, '216': { city: 'Cleveland', state: 'OH', tz: 'Eastern' },
  '217': { city: 'Springfield', state: 'IL', tz: 'Central' }, '218': { city: 'Duluth', state: 'MN', tz: 'Central' },
  '219': { city: 'Gary', state: 'IN', tz: 'Central' }, '220': { city: 'Newark', state: 'OH', tz: 'Eastern' },
  '223': { city: 'Lancaster', state: 'PA', tz: 'Eastern' }, '224': { city: 'Elgin', state: 'IL', tz: 'Central' },
  '225': { city: 'Baton Rouge', state: 'LA', tz: 'Central' }, '228': { city: 'Gulfport', state: 'MS', tz: 'Central' },
  '229': { city: 'Albany', state: 'GA', tz: 'Eastern' }, '231': { city: 'Muskegon', state: 'MI', tz: 'Eastern' },
  '234': { city: 'Akron', state: 'OH', tz: 'Eastern' }, '239': { city: 'Fort Myers', state: 'FL', tz: 'Eastern' },
  '240': { city: 'Germantown', state: 'MD', tz: 'Eastern' }, '248': { city: 'Troy', state: 'MI', tz: 'Eastern' },
  '251': { city: 'Mobile', state: 'AL', tz: 'Central' }, '252': { city: 'Greenville', state: 'NC', tz: 'Eastern' },
  '253': { city: 'Tacoma', state: 'WA', tz: 'Pacific' }, '254': { city: 'Killeen', state: 'TX', tz: 'Central' },
  '256': { city: 'Huntsville', state: 'AL', tz: 'Central' }, '260': { city: 'Fort Wayne', state: 'IN', tz: 'Eastern' },
  '262': { city: 'Kenosha', state: 'WI', tz: 'Central' }, '267': { city: 'Philadelphia', state: 'PA', tz: 'Eastern' },
  '269': { city: 'Kalamazoo', state: 'MI', tz: 'Eastern' }, '270': { city: 'Bowling Green', state: 'KY', tz: 'Central' },
  '272': { city: 'Scranton', state: 'PA', tz: 'Eastern' }, '276': { city: 'Bristol', state: 'VA', tz: 'Eastern' },
  '281': { city: 'Houston', state: 'TX', tz: 'Central' }, '301': { city: 'Rockville', state: 'MD', tz: 'Eastern' },
  '302': { city: 'Wilmington', state: 'DE', tz: 'Eastern' }, '303': { city: 'Denver', state: 'CO', tz: 'Mountain' },
  '304': { city: 'Charleston', state: 'WV', tz: 'Eastern' }, '305': { city: 'Miami', state: 'FL', tz: 'Eastern' },
  '307': { city: 'Cheyenne', state: 'WY', tz: 'Mountain' }, '308': { city: 'Grand Island', state: 'NE', tz: 'Central' },
  '309': { city: 'Peoria', state: 'IL', tz: 'Central' }, '310': { city: 'Los Angeles', state: 'CA', tz: 'Pacific' },
  '312': { city: 'Chicago', state: 'IL', tz: 'Central' }, '313': { city: 'Detroit', state: 'MI', tz: 'Eastern' },
  '314': { city: 'St. Louis', state: 'MO', tz: 'Central' }, '315': { city: 'Syracuse', state: 'NY', tz: 'Eastern' },
  '316': { city: 'Wichita', state: 'KS', tz: 'Central' }, '317': { city: 'Indianapolis', state: 'IN', tz: 'Eastern' },
  '318': { city: 'Shreveport', state: 'LA', tz: 'Central' }, '319': { city: 'Cedar Rapids', state: 'IA', tz: 'Central' },
  '320': { city: 'St. Cloud', state: 'MN', tz: 'Central' }, '321': { city: 'Orlando', state: 'FL', tz: 'Eastern' },
  '323': { city: 'Los Angeles', state: 'CA', tz: 'Pacific' }, '325': { city: 'Abilene', state: 'TX', tz: 'Central' },
  '330': { city: 'Akron', state: 'OH', tz: 'Eastern' }, '331': { city: 'Aurora', state: 'IL', tz: 'Central' },
  '334': { city: 'Montgomery', state: 'AL', tz: 'Central' }, '336': { city: 'Greensboro', state: 'NC', tz: 'Eastern' },
  '337': { city: 'Lafayette', state: 'LA', tz: 'Central' }, '339': { city: 'Framingham', state: 'MA', tz: 'Eastern' },
  '346': { city: 'Houston', state: 'TX', tz: 'Central' }, '347': { city: 'New York', state: 'NY', tz: 'Eastern' },
  '351': { city: 'Lowell', state: 'MA', tz: 'Eastern' }, '352': { city: 'Gainesville', state: 'FL', tz: 'Eastern' },
  '360': { city: 'Vancouver', state: 'WA', tz: 'Pacific' }, '361': { city: 'Corpus Christi', state: 'TX', tz: 'Central' },
  '385': { city: 'Salt Lake City', state: 'UT', tz: 'Mountain' }, '386': { city: 'Daytona Beach', state: 'FL', tz: 'Eastern' },
  '401': { city: 'Providence', state: 'RI', tz: 'Eastern' }, '402': { city: 'Omaha', state: 'NE', tz: 'Central' },
  '404': { city: 'Atlanta', state: 'GA', tz: 'Eastern' }, '405': { city: 'Oklahoma City', state: 'OK', tz: 'Central' },
  '406': { city: 'Billings', state: 'MT', tz: 'Mountain' }, '407': { city: 'Orlando', state: 'FL', tz: 'Eastern' },
  '408': { city: 'San Jose', state: 'CA', tz: 'Pacific' }, '409': { city: 'Beaumont', state: 'TX', tz: 'Central' },
  '410': { city: 'Baltimore', state: 'MD', tz: 'Eastern' }, '412': { city: 'Pittsburgh', state: 'PA', tz: 'Eastern' },
  '413': { city: 'Springfield', state: 'MA', tz: 'Eastern' }, '414': { city: 'Milwaukee', state: 'WI', tz: 'Central' },
  '415': { city: 'San Francisco', state: 'CA', tz: 'Pacific' }, '416': { city: 'Toronto', state: 'ON', tz: 'Eastern' },
  '417': { city: 'Springfield', state: 'MO', tz: 'Central' }, '418': { city: 'Quebec City', state: 'QC', tz: 'Eastern' },
  '419': { city: 'Toledo', state: 'OH', tz: 'Eastern' }, '423': { city: 'Chattanooga', state: 'TN', tz: 'Eastern' },
  '424': { city: 'Los Angeles', state: 'CA', tz: 'Pacific' }, '425': { city: 'Bellevue', state: 'WA', tz: 'Pacific' },
  '430': { city: 'Tyler', state: 'TX', tz: 'Central' }, '432': { city: 'Midland', state: 'TX', tz: 'Central' },
  '434': { city: 'Lynchburg', state: 'VA', tz: 'Eastern' }, '435': { city: 'St. George', state: 'UT', tz: 'Mountain' },
  '440': { city: 'Parma', state: 'OH', tz: 'Eastern' }, '442': { city: 'Oceanside', state: 'CA', tz: 'Pacific' },
  '443': { city: 'Baltimore', state: 'MD', tz: 'Eastern' }, '458': { city: 'Eugene', state: 'OR', tz: 'Pacific' },
  '469': { city: 'Dallas', state: 'TX', tz: 'Central' }, '470': { city: 'Atlanta', state: 'GA', tz: 'Eastern' },
  '475': { city: 'Bridgeport', state: 'CT', tz: 'Eastern' }, '478': { city: 'Macon', state: 'GA', tz: 'Eastern' },
  '479': { city: 'Fort Smith', state: 'AR', tz: 'Central' }, '480': { city: 'Mesa', state: 'AZ', tz: 'Mountain' },
  '484': { city: 'Allentown', state: 'PA', tz: 'Eastern' }, '501': { city: 'Little Rock', state: 'AR', tz: 'Central' },
  '502': { city: 'Louisville', state: 'KY', tz: 'Eastern' }, '503': { city: 'Portland', state: 'OR', tz: 'Pacific' },
  '504': { city: 'New Orleans', state: 'LA', tz: 'Central' }, '505': { city: 'Albuquerque', state: 'NM', tz: 'Mountain' },
  '507': { city: 'Rochester', state: 'MN', tz: 'Central' }, '508': { city: 'Worcester', state: 'MA', tz: 'Eastern' },
  '509': { city: 'Spokane', state: 'WA', tz: 'Pacific' }, '510': { city: 'Oakland', state: 'CA', tz: 'Pacific' },
  '512': { city: 'Austin', state: 'TX', tz: 'Central' }, '513': { city: 'Cincinnati', state: 'OH', tz: 'Eastern' },
  '515': { city: 'Des Moines', state: 'IA', tz: 'Central' }, '516': { city: 'Hempstead', state: 'NY', tz: 'Eastern' },
  '517': { city: 'Lansing', state: 'MI', tz: 'Eastern' }, '518': { city: 'Albany', state: 'NY', tz: 'Eastern' },
  '520': { city: 'Tucson', state: 'AZ', tz: 'Mountain' }, '530': { city: 'Redding', state: 'CA', tz: 'Pacific' },
  '531': { city: 'Omaha', state: 'NE', tz: 'Central' }, '534': { city: 'Eau Claire', state: 'WI', tz: 'Central' },
  '539': { city: 'Tulsa', state: 'OK', tz: 'Central' }, '540': { city: 'Roanoke', state: 'VA', tz: 'Eastern' },
  '541': { city: 'Eugene', state: 'OR', tz: 'Pacific' }, '551': { city: 'Jersey City', state: 'NJ', tz: 'Eastern' },
  '559': { city: 'Fresno', state: 'CA', tz: 'Pacific' }, '561': { city: 'West Palm Beach', state: 'FL', tz: 'Eastern' },
  '562': { city: 'Long Beach', state: 'CA', tz: 'Pacific' }, '563': { city: 'Davenport', state: 'IA', tz: 'Central' },
  '567': { city: 'Toledo', state: 'OH', tz: 'Eastern' }, '571': { city: 'Arlington', state: 'VA', tz: 'Eastern' },
  '573': { city: 'Columbia', state: 'MO', tz: 'Central' }, '574': { city: 'South Bend', state: 'IN', tz: 'Eastern' },
  '580': { city: 'Lawton', state: 'OK', tz: 'Central' }, '585': { city: 'Rochester', state: 'NY', tz: 'Eastern' },
  '586': { city: 'Warren', state: 'MI', tz: 'Eastern' }, '601': { city: 'Jackson', state: 'MS', tz: 'Central' },
  '602': { city: 'Phoenix', state: 'AZ', tz: 'Mountain' }, '603': { city: 'Manchester', state: 'NH', tz: 'Eastern' },
  '605': { city: 'Sioux Falls', state: 'SD', tz: 'Central' }, '606': { city: 'Ashland', state: 'KY', tz: 'Eastern' },
  '607': { city: 'Binghamton', state: 'NY', tz: 'Eastern' }, '608': { city: 'Madison', state: 'WI', tz: 'Central' },
  '609': { city: 'Trenton', state: 'NJ', tz: 'Eastern' }, '610': { city: 'Allentown', state: 'PA', tz: 'Eastern' },
  '612': { city: 'Minneapolis', state: 'MN', tz: 'Central' }, '614': { city: 'Columbus', state: 'OH', tz: 'Eastern' },
  '615': { city: 'Nashville', state: 'TN', tz: 'Central' }, '616': { city: 'Grand Rapids', state: 'MI', tz: 'Eastern' },
  '617': { city: 'Boston', state: 'MA', tz: 'Eastern' }, '618': { city: 'Belleville', state: 'IL', tz: 'Central' },
  '619': { city: 'San Diego', state: 'CA', tz: 'Pacific' }, '620': { city: 'Hutchinson', state: 'KS', tz: 'Central' },
  '623': { city: 'Glendale', state: 'AZ', tz: 'Mountain' }, '626': { city: 'Pasadena', state: 'CA', tz: 'Pacific' },
  '628': { city: 'San Francisco', state: 'CA', tz: 'Pacific' }, '629': { city: 'Nashville', state: 'TN', tz: 'Central' },
  '630': { city: 'Naperville', state: 'IL', tz: 'Central' }, '631': { city: 'Brentwood', state: 'NY', tz: 'Eastern' },
  '636': { city: "O'Fallon", state: 'MO', tz: 'Central' }, '641': { city: 'Mason City', state: 'IA', tz: 'Central' },
  '646': { city: 'New York', state: 'NY', tz: 'Eastern' }, '650': { city: 'San Mateo', state: 'CA', tz: 'Pacific' },
  '651': { city: 'St. Paul', state: 'MN', tz: 'Central' }, '657': { city: 'Anaheim', state: 'CA', tz: 'Pacific' },
  '660': { city: 'Sedalia', state: 'MO', tz: 'Central' }, '661': { city: 'Bakersfield', state: 'CA', tz: 'Pacific' },
  '662': { city: 'Tupelo', state: 'MS', tz: 'Central' }, '667': { city: 'Baltimore', state: 'MD', tz: 'Eastern' },
  '669': { city: 'San Jose', state: 'CA', tz: 'Pacific' }, '678': { city: 'Atlanta', state: 'GA', tz: 'Eastern' },
  '681': { city: 'Charleston', state: 'WV', tz: 'Eastern' }, '682': { city: 'Fort Worth', state: 'TX', tz: 'Central' },
  '701': { city: 'Fargo', state: 'ND', tz: 'Central' }, '702': { city: 'Las Vegas', state: 'NV', tz: 'Pacific' },
  '703': { city: 'Arlington', state: 'VA', tz: 'Eastern' }, '704': { city: 'Charlotte', state: 'NC', tz: 'Eastern' },
  '706': { city: 'Augusta', state: 'GA', tz: 'Eastern' }, '707': { city: 'Santa Rosa', state: 'CA', tz: 'Pacific' },
  '708': { city: 'Cicero', state: 'IL', tz: 'Central' }, '712': { city: 'Sioux City', state: 'IA', tz: 'Central' },
  '713': { city: 'Houston', state: 'TX', tz: 'Central' }, '714': { city: 'Anaheim', state: 'CA', tz: 'Pacific' },
  '715': { city: 'Eau Claire', state: 'WI', tz: 'Central' }, '716': { city: 'Buffalo', state: 'NY', tz: 'Eastern' },
  '717': { city: 'Lancaster', state: 'PA', tz: 'Eastern' }, '718': { city: 'New York', state: 'NY', tz: 'Eastern' },
  '719': { city: 'Colorado Springs', state: 'CO', tz: 'Mountain' },
  '720': { city: 'Denver', state: 'CO', tz: 'Mountain' }, '724': { city: 'New Castle', state: 'PA', tz: 'Eastern' },
  '725': { city: 'Las Vegas', state: 'NV', tz: 'Pacific' }, '727': { city: 'St. Petersburg', state: 'FL', tz: 'Eastern' },
  '731': { city: 'Jackson', state: 'TN', tz: 'Central' }, '732': { city: 'New Brunswick', state: 'NJ', tz: 'Eastern' },
  '734': { city: 'Ann Arbor', state: 'MI', tz: 'Eastern' }, '737': { city: 'Austin', state: 'TX', tz: 'Central' },
  '740': { city: 'Lancaster', state: 'OH', tz: 'Eastern' }, '743': { city: 'Greensboro', state: 'NC', tz: 'Eastern' },
  '747': { city: 'Burbank', state: 'CA', tz: 'Pacific' }, '754': { city: 'Fort Lauderdale', state: 'FL', tz: 'Eastern' },
  '757': { city: 'Virginia Beach', state: 'VA', tz: 'Eastern' }, '760': { city: 'Oceanside', state: 'CA', tz: 'Pacific' },
  '762': { city: 'Augusta', state: 'GA', tz: 'Eastern' }, '763': { city: 'Brooklyn Park', state: 'MN', tz: 'Central' },
  '765': { city: 'Muncie', state: 'IN', tz: 'Eastern' }, '769': { city: 'Jackson', state: 'MS', tz: 'Central' },
  '770': { city: 'Roswell', state: 'GA', tz: 'Eastern' }, '772': { city: 'Port St. Lucie', state: 'FL', tz: 'Eastern' },
  '773': { city: 'Chicago', state: 'IL', tz: 'Central' }, '774': { city: 'Worcester', state: 'MA', tz: 'Eastern' },
  '775': { city: 'Reno', state: 'NV', tz: 'Pacific' }, '779': { city: 'Rockford', state: 'IL', tz: 'Central' },
  '781': { city: 'Quincy', state: 'MA', tz: 'Eastern' }, '785': { city: 'Topeka', state: 'KS', tz: 'Central' },
  '786': { city: 'Miami', state: 'FL', tz: 'Eastern' }, '801': { city: 'Salt Lake City', state: 'UT', tz: 'Mountain' },
  '802': { city: 'Burlington', state: 'VT', tz: 'Eastern' }, '803': { city: 'Columbia', state: 'SC', tz: 'Eastern' },
  '804': { city: 'Richmond', state: 'VA', tz: 'Eastern' }, '805': { city: 'Oxnard', state: 'CA', tz: 'Pacific' },
  '806': { city: 'Lubbock', state: 'TX', tz: 'Central' }, '808': { city: 'Honolulu', state: 'HI', tz: 'Hawaii' },
  '810': { city: 'Flint', state: 'MI', tz: 'Eastern' }, '812': { city: 'Evansville', state: 'IN', tz: 'Eastern' },
  '813': { city: 'Tampa', state: 'FL', tz: 'Eastern' }, '814': { city: 'Erie', state: 'PA', tz: 'Eastern' },
  '815': { city: 'Rockford', state: 'IL', tz: 'Central' }, '816': { city: 'Kansas City', state: 'MO', tz: 'Central' },
  '817': { city: 'Fort Worth', state: 'TX', tz: 'Central' }, '818': { city: 'Burbank', state: 'CA', tz: 'Pacific' },
  '828': { city: 'Asheville', state: 'NC', tz: 'Eastern' }, '830': { city: 'New Braunfels', state: 'TX', tz: 'Central' },
  '831': { city: 'Salinas', state: 'CA', tz: 'Pacific' }, '832': { city: 'Houston', state: 'TX', tz: 'Central' },
  '843': { city: 'Charleston', state: 'SC', tz: 'Eastern' }, '845': { city: 'New City', state: 'NY', tz: 'Eastern' },
  '847': { city: 'Schaumburg', state: 'IL', tz: 'Central' }, '848': { city: 'New Brunswick', state: 'NJ', tz: 'Eastern' },
  '850': { city: 'Tallahassee', state: 'FL', tz: 'Eastern' }, '856': { city: 'Camden', state: 'NJ', tz: 'Eastern' },
  '857': { city: 'Boston', state: 'MA', tz: 'Eastern' }, '858': { city: 'San Diego', state: 'CA', tz: 'Pacific' },
  '859': { city: 'Lexington', state: 'KY', tz: 'Eastern' }, '860': { city: 'Hartford', state: 'CT', tz: 'Eastern' },
  '862': { city: 'Newark', state: 'NJ', tz: 'Eastern' }, '863': { city: 'Lakeland', state: 'FL', tz: 'Eastern' },
  '864': { city: 'Greenville', state: 'SC', tz: 'Eastern' }, '865': { city: 'Knoxville', state: 'TN', tz: 'Eastern' },
  '870': { city: 'Jonesboro', state: 'AR', tz: 'Central' }, '878': { city: 'Pittsburgh', state: 'PA', tz: 'Eastern' },
  '901': { city: 'Memphis', state: 'TN', tz: 'Central' }, '903': { city: 'Tyler', state: 'TX', tz: 'Central' },
  '904': { city: 'Jacksonville', state: 'FL', tz: 'Eastern' }, '906': { city: 'Marquette', state: 'MI', tz: 'Eastern' },
  '907': { city: 'Anchorage', state: 'AK', tz: 'Alaska' }, '908': { city: 'Elizabeth', state: 'NJ', tz: 'Eastern' },
  '909': { city: 'San Bernardino', state: 'CA', tz: 'Pacific' }, '910': { city: 'Fayetteville', state: 'NC', tz: 'Eastern' },
  '912': { city: 'Savannah', state: 'GA', tz: 'Eastern' }, '913': { city: 'Kansas City', state: 'KS', tz: 'Central' },
  '914': { city: 'Yonkers', state: 'NY', tz: 'Eastern' }, '915': { city: 'El Paso', state: 'TX', tz: 'Mountain' },
  '916': { city: 'Sacramento', state: 'CA', tz: 'Pacific' }, '917': { city: 'New York', state: 'NY', tz: 'Eastern' },
  '918': { city: 'Tulsa', state: 'OK', tz: 'Central' }, '919': { city: 'Raleigh', state: 'NC', tz: 'Eastern' },
  '920': { city: 'Green Bay', state: 'WI', tz: 'Central' }, '925': { city: 'Concord', state: 'CA', tz: 'Pacific' },
  '928': { city: 'Yuma', state: 'AZ', tz: 'Mountain' }, '929': { city: 'New York', state: 'NY', tz: 'Eastern' },
  '931': { city: 'Clarksville', state: 'TN', tz: 'Central' }, '936': { city: 'Conroe', state: 'TX', tz: 'Central' },
  '937': { city: 'Dayton', state: 'OH', tz: 'Eastern' }, '938': { city: 'Huntsville', state: 'AL', tz: 'Central' },
  '940': { city: 'Denton', state: 'TX', tz: 'Central' }, '941': { city: 'Sarasota', state: 'FL', tz: 'Eastern' },
  '947': { city: 'Troy', state: 'MI', tz: 'Eastern' }, '949': { city: 'Irvine', state: 'CA', tz: 'Pacific' },
  '951': { city: 'Riverside', state: 'CA', tz: 'Pacific' }, '952': { city: 'Bloomington', state: 'MN', tz: 'Central' },
  '954': { city: 'Fort Lauderdale', state: 'FL', tz: 'Eastern' }, '956': { city: 'Laredo', state: 'TX', tz: 'Central' },
  '959': { city: 'Hartford', state: 'CT', tz: 'Eastern' }, '970': { city: 'Fort Collins', state: 'CO', tz: 'Mountain' },
  '971': { city: 'Portland', state: 'OR', tz: 'Pacific' }, '972': { city: 'Dallas', state: 'TX', tz: 'Central' },
  '973': { city: 'Newark', state: 'NJ', tz: 'Eastern' }, '978': { city: 'Lowell', state: 'MA', tz: 'Eastern' },
  '979': { city: 'College Station', state: 'TX', tz: 'Central' }, '980': { city: 'Charlotte', state: 'NC', tz: 'Eastern' },
  '984': { city: 'Raleigh', state: 'NC', tz: 'Eastern' }, '985': { city: 'Houma', state: 'LA', tz: 'Central' },
};

export default function AreaCodeFinder() {
  const [q, setQ] = useState('');
  const results = q.length >= 2 ? Object.entries(areaCodes).filter(([code, info]) => code.includes(q) || info.city.toLowerCase().includes(q.toLowerCase()) || info.state.toLowerCase().includes(q.toLowerCase())) : [];
  return (
    <div className="space-y-4">
      <input type="text" value={q} onChange={e => setQ(e.target.value)} placeholder="Enter area code, city, or state..." className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-primary outline-none text-lg" />
      {q.length >= 2 && (
        <div className="border border-gray-200 rounded-lg overflow-hidden">
          {results.length > 0 ? (
            <table className="w-full text-sm">
              <thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left font-semibold">Area Code</th><th className="px-4 py-3 text-left font-semibold">City</th><th className="px-4 py-3 text-left font-semibold">State</th><th className="px-4 py-3 text-left font-semibold">Timezone</th></tr></thead>
              <tbody className="divide-y divide-gray-100">
                {results.slice(0, 50).map(([code, info]) => (
                  <tr key={code} className="hover:bg-blue-50 transition-colors">
                    <td className="px-4 py-3 font-bold text-primary">{code}</td>
                    <td className="px-4 py-3 font-medium">{info.city}</td>
                    <td className="px-4 py-3">{info.state}</td>
                    <td className="px-4 py-3 text-gray-500">{info.tz}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : <div className="p-8 text-center text-gray-400">No results found.</div>}
        </div>
      )}
      {q.length < 2 && <p className="text-center text-gray-400 py-8">Type at least 2 characters to search.</p>}
    </div>
  );
}
